export const PORTFOLIO_GALAXY_CONFIG = {
  mouseRepulsion: false,
  mouseInteraction: true,
  density: 0.2,
  glowIntensity: 0.2,
  saturation: 0,
  hueShift: 140,
  twinkleIntensity: 0.5,
  rotationSpeed: 0,
  repulsionStrength: 2,
  autoCenterRepulsion: 0,
  starSpeed: 0.5,
  speed: 0.1,
  pixelRatio: 1.25,
  targetFps: 24,
  maxPixelCount: 2600000,
};

export const PORTFOLIO_WAVES_CONFIG = {
  lineColor: "#a4a4a4",
  backgroundColor: "transparent",
  waveSpeedX: 0.008,
  waveSpeedY: 0.008,
  waveAmpX: 28,
  waveAmpY: 14,
  friction: 0.72,
  tension: 0.005,
  maxCursorMove: 160,
  xGap: 28,
  yGap: 16,
  pixelRatio: 1.25,
  targetFps: 24,
  maxPixelCount: 2600000,
  mouseInteraction: true,
};
