export const QUALITY_MODES = {
  quality: { label: "Quality", dpr: 1.5, density: 1, fps: 60 },
  balanced: { label: "Balanced", dpr: 1, density: 0.68, fps: 45 },
  low: { label: "Low Power", dpr: 0.75, density: 0.42, fps: 30 },
};

export const EXPERIMENTS = [
  {
    id: "galaxy",
    index: "01",
    title: "Galaxy",
    shortDescription: "A slow spiral system built from density, light and depth.",
    category: "Fields",
    technologies: ["THREE.JS", "OGL"],
    status: "Study",
    renderer: "OGL / WebGL",
    origin: [
      { relationship: "Used in", projectName: "Hero backdrop", projectUrl: "/" },
      { relationship: "Used in", projectName: "Footer dark-mode backdrop", projectUrl: "/" },
    ],
    controls: [
      { key: "density", label: "Star density", min: 0.45, max: 1.2, step: 0.05, value: 0.86 },
      { key: "twinkle", label: "Twinkle", min: 0, max: 0.8, step: 0.05, value: 0.32 },
      { key: "repulsion", label: "Pointer repulsion", min: 0.2, max: 4, step: 0.1, value: 1.8 },
      { key: "rotation", label: "Rotation speed", min: 0, max: 0.24, step: 0.01, value: 0.08 },
    ],
  },
  {
    id: "waves",
    index: "02",
    title: "Waves",
    shortDescription: "A continuous line field whose ridges carry the light.",
    category: "Fields",
    technologies: ["CANVAS 2D"],
    status: "Study",
    renderer: "Canvas 2D",
    origin: [
      { relationship: "Used in", projectName: "Hero backdrop", projectUrl: "/" },
      { relationship: "Used in", projectName: "Contact section", projectUrl: "/#contact" },
    ],
    controls: [
      { key: "ampX", label: "Horizontal amplitude", min: 12, max: 58, step: 1, value: 34 },
      { key: "ampY", label: "Vertical amplitude", min: 6, max: 38, step: 1, value: 18 },
      { key: "spacing", label: "Line spacing", min: 18, max: 48, step: 1, value: 28 },
      { key: "tension", label: "Pointer tension", min: 0.002, max: 0.018, step: 0.001, value: 0.007 },
    ],
  },
  {
    id: "refraction",
    index: "03",
    title: "Refraction",
    shortDescription: "A wire surface bends around a moving lens of pressure.",
    category: "Fields",
    technologies: ["THREE.JS", "WEBGL"],
    status: "Study",
    renderer: "Three.js / WebGL",
    controls: [
      { key: "strength", label: "Lens strength", min: 0.2, max: 1.5, step: 0.05, value: 0.8 },
      { key: "radius", label: "Lens radius", min: 0.2, max: 1.1, step: 0.05, value: 0.62 },
      { key: "recovery", label: "Recovery", min: 0.05, max: 0.4, step: 0.01, value: 0.16 },
    ],
  },
  {
    id: "text-pressure",
    index: "04",
    title: "Text Pressure",
    shortDescription: "Variable weight and width gather around the pointer.",
    category: "Type",
    technologies: ["CSS", "TYPOGRAPHY"],
    status: "Study",
    renderer: "DOM / CSS",
    origin: [
      { relationship: "Used in", projectName: "Hero name treatment", projectUrl: "/" },
    ],
    controls: [
      { key: "weight", label: "Base weight", min: 80, max: 420, step: 10, value: 120 },
      { key: "maxWeight", label: "Peak weight", min: 560, max: 900, step: 10, value: 900 },
      { key: "response", label: "Response rate", min: 30, max: 60, step: 5, value: 60 },
    ],
  },
  {
    id: "pressure-field",
    index: "05",
    title: "Pressure Field",
    shortDescription: "Multiline text reflows as if the pointer has physical mass.",
    category: "Type",
    technologies: ["PRETEXT", "CANVAS"],
    status: "Study",
    renderer: "Pretext / Canvas 2D",
    controls: [
      { key: "radius", label: "Pressure radius", min: 80, max: 260, step: 10, value: 170 },
      { key: "strength", label: "Pressure strength", min: 0.2, max: 1.4, step: 0.05, value: 0.8 },
      { key: "recovery", label: "Recovery speed", min: 0.04, max: 0.3, step: 0.01, value: 0.12 },
      { key: "mode", label: "Typography mode", value: "elastic", options: [
        { value: "flow", label: "Flow" },
        { value: "compression", label: "Compression" },
        { value: "elastic", label: "Elastic" },
      ] },
    ],
  },
  {
    id: "particle-type",
    index: "06",
    title: "Typographic Particle Formation",
    shortDescription: "Thousands of points remember the shape of language.",
    category: "Type",
    technologies: ["THREE.JS", "CANVAS"],
    status: "Study",
    renderer: "Three.js / WebGL",
    controls: [
      { key: "dispersion", label: "Dispersion", min: 0, max: 1.4, step: 0.05, value: 0.28 },
      { key: "depth", label: "Particle depth", min: 0.1, max: 1.2, step: 0.05, value: 0.55 },
      { key: "cohesion", label: "Cohesion", min: 0.03, max: 0.22, step: 0.01, value: 0.1 },
    ],
  },
  {
    id: "cursor-trail",
    index: "07",
    title: "Cursor Trail",
    shortDescription: "Two real cursor systems: fluid simulation and menu dot field.",
    category: "Motion",
    technologies: ["WEBGL", "CANVAS 2D"],
    status: "Study",
    renderer: "WebGL / Canvas 2D",
    origin: [
      { relationship: "Built for", projectName: "SplashCursor component" },
      { relationship: "Used in", projectName: "Menu pointer trail", projectUrl: "/" },
    ],
    controls: [
      { key: "mode", label: "Trail mode", value: "fluid", options: [
        { value: "fluid", label: "Fluid" },
        { value: "dots", label: "Dot Field" },
      ] },
      { key: "radius", label: "Native radius", min: 0.06, max: 0.32, step: 0.01, value: 0.16 },
      { key: "force", label: "Native force", min: 1600, max: 9000, step: 100, value: 5200 },
      { key: "decay", label: "Native decay", min: 2, max: 6, step: 0.1, value: 3.4 },
    ],
  },
  {
    id: "cursor-morph",
    index: "08",
    title: "Cursor Morph Lab",
    shortDescription: "The portfolio cursor resolves intent instead of swapping assets.",
    category: "Motion",
    technologies: ["SVG", "POINTER EVENTS"],
    status: "Live",
    renderer: "SVG / DOM",
    origin: [
      { relationship: "Used in", projectName: "Portfolio cursor system", projectUrl: "/" },
      { relationship: "Built for", projectName: "SVG / pointer events / motion" },
    ],
    controls: [
      { key: "morph", label: "Morph speed", min: 0.12, max: 0.8, step: 0.02, value: 0.32 },
      { key: "roundness", label: "Vertex roundness", min: 0, max: 1, step: 0.05, value: 0.75 },
      { key: "fill", label: "Fill speed", min: 0.12, max: 0.7, step: 0.02, value: 0.28 },
      { key: "pulse", label: "Pulse duration", min: 0.35, max: 1.4, step: 0.05, value: 0.7 },
    ],
  },
  {
    id: "atlas-field",
    index: "09",
    title: "Atlas Field",
    shortDescription: "A curved image horizon turns browsing into spatial focus.",
    category: "Studies",
    technologies: ["THREE.JS", "WEBGL"],
    status: "Project Study",
    renderer: "Three.js / WebGL",
    origin: [
      { relationship: "Inspired by", projectName: "Movie Atlas", projectUrl: "https://github.com/iice257/What-to-watch" },
    ],
    controls: [
      { key: "curvature", label: "Field curvature", min: 0.15, max: 1.2, step: 0.05, value: 0.68 },
      { key: "focus", label: "Focus strength", min: 0.1, max: 1.2, step: 0.05, value: 0.62 },
      { key: "depth", label: "Camera depth", min: 0.7, max: 1.5, step: 0.05, value: 1 },
      { key: "motion", label: "Motion intensity", min: 0, max: 1, step: 0.05, value: 0.35 },
    ],
  },
  {
    id: "signal-field",
    index: "10",
    title: "Signal Field",
    shortDescription: "A synthetic signal displaces a spatial frequency terrain.",
    category: "Studies",
    technologies: ["THREE.JS", "WEB AUDIO"],
    status: "Project Study",
    renderer: "Three.js / Web Audio",
    origin: [
      { relationship: "Inspired by", projectName: "VISUALICER", projectUrl: "https://github.com/iice257/VISUALICER" },
    ],
    controls: [
      { key: "source", label: "Input source", value: "synthetic", options: [
        { value: "synthetic", label: "Synthetic signal" },
        { value: "microphone", label: "Microphone (optional)" },
      ] },
      { key: "sensitivity", label: "Sensitivity", min: 0.2, max: 1.8, step: 0.05, value: 0.9 },
      { key: "response", label: "Response mode", value: "terrain", options: [
        { value: "terrain", label: "Spectral terrain" },
        { value: "bands", label: "Frequency bands" },
        { value: "wave", label: "Wave sculpture" },
      ] },
      { key: "terrain", label: "Terrain depth", min: 0.3, max: 1.5, step: 0.05, value: 0.85 },
    ],
  },
  {
    id: "ascii-text",
    index: "11",
    title: "ASCIIText",
    shortDescription: "A live Three.js text plane translated into an ASCII surface.",
    category: "Type",
    technologies: ["THREE.JS", "CANVAS"],
    status: "Prototype",
    renderer: "Three.js / Canvas",
    controls: [
      { key: "asciiFontSize", label: "ASCII cell size", min: 6, max: 14, step: 1, value: 8 },
      { key: "textFontSize", label: "Text scale", min: 120, max: 300, step: 10, value: 210 },
      { key: "planeBaseHeight", label: "Plane height", min: 5, max: 12, step: 0.5, value: 8 },
      { key: "enableWaves", label: "Wave deformation", value: "on", options: [
        { value: "on", label: "On" },
        { value: "off", label: "Off" },
      ] },
    ],
  },
  {
    id: "metallic-paint",
    index: "12",
    title: "MetallicPaint",
    shortDescription: "A WebGL material pass turns a mask into liquid graphite.",
    category: "Materials",
    technologies: ["WEBGL2"],
    status: "Prototype",
    renderer: "WebGL2",
    origin: [
      { relationship: "Built for", projectName: "Project visual system", projectUrl: "/projects" },
    ],
    controls: [
      { key: "scale", label: "Pattern scale", min: 2, max: 6, step: 0.1, value: 3.6 },
      { key: "liquid", label: "Liquid depth", min: 0.2, max: 1.2, step: 0.05, value: 0.62 },
      { key: "refraction", label: "Refraction", min: 0.004, max: 0.03, step: 0.001, value: 0.012 },
      { key: "contour", label: "Contour", min: 0, max: 0.55, step: 0.01, value: 0.2 },
    ],
  },
];

export const getDefaultParams = (experiment) => Object.fromEntries(
  experiment.controls.map((control) => [control.key, control.value])
);
